# Generated by Django 4.1.2 on 2023-06-08 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='نام')),
                ('text', models.TextField(verbose_name='پیام')),
                ('email', models.EmailField(max_length=254, verbose_name='رایانامه')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='برای درج شماره تماس لطفا فقط عدد وارد کنید', regex='^[0-9]')], verbose_name='شماره تماس')),
                ('is_ready', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج پیام')),
            ],
            options={
                'verbose_name': 'بخش پیام ها',
                'verbose_name_plural': 'بخش پیام ها',
            },
        ),
    ]
