# Generated by Django 4.1.2 on 2023-04-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price'], 'verbose_name': 'کالا', 'verbose_name_plural': 'کالاها'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه ها'},
        ),
        migrations.AddField(
            model_name='review',
            name='replay',
            field=models.TextField(blank=True, null=True, verbose_name='پسخ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved_comment',
            field=models.BooleanField(default=False, verbose_name='نمایش پیام'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=255, verbose_name='بازدیدکننده'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='پیام'),
        ),
    ]
