# Generated by Django 4.1.2 on 2023-05-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_visits_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدیدها'},
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip_address',
            field=models.CharField(max_length=255, verbose_name='آی پی آدرس بازدید کننده'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='نام محصول'),
        ),
    ]
